name: ci

on:
  schedule:
    - cron:  '0 0 * * *' # Runs at 12:00 AM every day

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./docker-compose/bettergpt/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: pawanosman/bettergpt:latest
